#set page(width: 120pt)
#set page(height:auto)
#set page(margin: 10pt)
#set text(size: 10pt)
#set page(width: 200pt, height: auto, margin: 10pt)
#set par(justify: true)
#set text(fill: gradient.conic(red, blue, angle: 45deg))
#lorem(30)
